import type { ExperienceService } from "../experience/service";
import type { ExperienceLearningRuntime } from "../experience/learning-runtime";
import type { AuthStore } from "../auth/store";
import type { ActivityEventFactory } from "../activity/recording/event-factory";
import type { ActivityQueryService } from "../activity/database/service";
import type { ActivityRecorder } from "../activity/recording/recorder";
import type { ActivityStore } from "../activity/recording/store";
import type { TerminalSnapshotShareService } from "../terminal/snapshot-share/service";
import type { TerminalActivityDependencies } from "../terminal/runtime/activity-events";
import type { EvolutionAnalysisStore } from "../evolution/analysis-store";
import type { EvolutionContextPackStore } from "../evolution/context-pack-store";
import type { KnowledgeInboxService } from "../knowledge-inbox/service";
import type { LocalBrowserService } from "../browser-local/service";
import type { DeviceMonitoringRuntime } from "../device-monitor/bootstrap";
import type { MobileLoginService } from "../auth/mobile-login";
import type { AuthService } from "../auth/service";
import type { AgentTeamService } from "../agent-team/service";
import type { AgentTeamModelConfigStore } from "../agent-team/runtime/model-config-store";
import type { LowDbTerminalQuickInputStore } from "../terminal/quick-input/lowdb-store";
import type { TerminalQuickInputService } from "../terminal/quick-input/service";
import type { PtyService } from "../terminal/runtime/pty-service";
import type { TerminalRuntimeRegistry } from "../terminal/runtime/registry";
import type { TmuxLifecycleCoordinator } from "../terminal/tmux/lifecycle-coordinator";
import type { TmuxOutputWatcher } from "../terminal/tmux/output-watcher";
import type { TmuxService } from "../terminal/tmux/service";
import type { TerminalSessionManager } from "../terminal/manager/manager";
import type { RuntimeStatusWorkspaceServiceManager } from "../runtime-status/workspace-service-manager";
import type { TerminalCompletionEventService } from "../terminal/completion/event-service";
import type { TerminalEventService } from "../terminal/state/terminal-event-service";
import type { TerminalStateService } from "../terminal/state/terminal-state-service";
import type { AppServerHistoryGateway } from "../work-history/app-server-history-gateway";
import type { WorkHistoryService } from "../work-history/work-history-service";
import type { AttentionService } from "../attention/attention-service";
import type { EvolutionActivationStore } from "../evolution/activation-store";
import type { EvolutionRuntime } from "../evolution/runtime";
import type { EvolutionService } from "../evolution/service";
import type { EvolutionToolTokenRegistry } from "../evolution/tools/token-registry";
import type { RaceService } from "../race/race-service";
import type { ScheduledTaskService } from "../scheduled-tasks/service";
import type { BackendRuntimeStatusService } from "../runtime-status/service";

export interface RuntimeServices extends DeviceMonitoringRuntime {
  start(controlPlaneBaseUrl: string): void;
  dispose(): Promise<void>;
  runtimeStatus: BackendRuntimeStatusService;
  activityStore: ActivityStore | null;
  activityRecorder: ActivityRecorder;
  activityQueryService: ActivityQueryService;
  activityEventFactory: ActivityEventFactory;
  terminalActivity: TerminalActivityDependencies;
  authStore: AuthStore;
  authService: AuthService;
  mobileLoginService: MobileLoginService;
  localBrowserService: LocalBrowserService;
  authCookieName: string;
  authSecureCookies: boolean;
  terminalSessionManager: TerminalSessionManager;
  terminalSnapshotShareService: TerminalSnapshotShareService;
  workspaceServiceManager: RuntimeStatusWorkspaceServiceManager;
  terminalQuickInputStore: LowDbTerminalQuickInputStore;
  terminalQuickInputService: TerminalQuickInputService;
  terminalStateService: TerminalStateService;
  agentTeamService: AgentTeamService;
  agentTeamModelConfigStore: AgentTeamModelConfigStore;
  raceService: RaceService;
  appServerHistoryGateway: AppServerHistoryGateway;
  workHistoryService: WorkHistoryService;
  terminalEventService: TerminalEventService;
  terminalCompletionEventService: TerminalCompletionEventService;
  attentionService: AttentionService;
  terminalRuntimeRegistry: TerminalRuntimeRegistry;
  tmuxLifecycleCoordinator: TmuxLifecycleCoordinator;
  ptyService: PtyService;
  tmuxService: TmuxService;
  tmuxOutputWatcher: TmuxOutputWatcher;
  tmuxSocketPathsToCleanOnShutdown: readonly string[];
  evolutionActivationStore: EvolutionActivationStore;
  evolutionAnalysisStore: EvolutionAnalysisStore | null;
  evolutionContextPackStore: EvolutionContextPackStore | null;
  evolutionToolTokenRegistry: EvolutionToolTokenRegistry;
  evolutionRuntime: EvolutionRuntime;
  evolutionService: EvolutionService;
  knowledgeInboxService: KnowledgeInboxService;
  experienceService: ExperienceService;
  experienceLearning: ExperienceLearningRuntime;
  scheduledTaskService: ScheduledTaskService;
}
