// Runweave managed Pi extension. Generated by pnpm agents:build; do not edit.

// plugins/pi/extensions/runweave.ts
import { spawnSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { readFileSync, realpathSync } from "node:fs";
import { chmod, mkdir, unlink } from "node:fs/promises";
import { createServer, request } from "node:http";
import { fileURLToPath } from "node:url";

// packages/agent-bridge/src/transport.ts
import { spawn } from "node:child_process";
import path from "node:path";
function createBridgeTransport(source, bundledBridge) {
  let delivery = Promise.resolve();
  return {
    publish(payload) {
      const serialized = JSON.stringify(payload);
      delivery = delivery.then(
        () => new Promise((resolve) => {
          const override = process.env.RUNWEAVE_AGENT_BRIDGE_ROOT;
          const bridge = override ? path.join(override, "runweave-hook-bridge.cjs") : bundledBridge;
          const child = spawn(
            process.execPath,
            [bridge, "--source", source],
            {
              stdio: ["pipe", "ignore", "ignore"]
            }
          );
          const timeout = setTimeout(() => child.kill(), 8e3);
          const finish = () => {
            clearTimeout(timeout);
            resolve();
          };
          child.stdin.on("error", () => {
          });
          child.once("error", finish);
          child.once("close", finish);
          child.stdin.end(serialized);
        })
      ).catch(() => {
      });
    },
    drain: () => delivery
  };
}

// plugins/pi/extensions/runweave.ts
import path2 from "node:path";
function runweave(pi) {
  const terminalSessionId = process.env.RUNWEAVE_TERMINAL_SESSION_ID;
  const tmuxSocket = process.env.TMUX?.split(",")[0];
  const pane = process.env.TMUX_PANE;
  if (!terminalSessionId || !tmuxSocket || !pane) return;
  let context;
  let closed = false;
  let waitingForUI = false;
  let sequence = 0;
  let runId = null;
  let outcome = null;
  let reply = "";
  const instanceId = randomUUID();
  const startedAt = (/* @__PURE__ */ new Date()).toISOString();
  const transport = createBridgeTransport(
    "pi",
    fileURLToPath(
      new URL("./bridge/runweave-hook-bridge.cjs", import.meta.url)
    )
  );
  let server;
  let socketPath;
  let ownsSocket = false;
  const applied = /* @__PURE__ */ new Map();
  function publish(ctx, event, hook, extra = {}) {
    if (closed) return;
    const fact = {
      version: 1,
      sessionId: ctx.sessionManager.getSessionId(),
      sessionFile: canonicalSessionFile(ctx.sessionManager.getSessionFile()),
      instanceId,
      startedAt,
      sequence: ++sequence,
      runId,
      leafId: ctx.sessionManager.getLeafId(),
      event,
      outcome
    };
    pi.appendEntry("runweave.lifecycle", {
      ...fact,
      terminalSessionId,
      tmuxPaneId: pane,
      operationId: process.env.RUNWEAVE_TERMINAL_AGENT_OPERATION_ID ?? null,
      hook,
      timestamp: (/* @__PURE__ */ new Date()).toISOString()
    });
    transport.publish({
      hook_event_name: hook,
      session_id: fact.sessionId,
      cwd: ctx.cwd,
      pi: fact,
      ...extra
    });
  }
  async function openEditor(ctx) {
    if (!ctx.hasUI) return;
    const directory = path2.join(
      "/tmp",
      `rw-pi-${process.getuid?.() ?? "user"}`
    );
    await mkdir(directory, { recursive: true, mode: 448 });
    await chmod(directory, 448);
    const key = createHash("sha256").update(`${tmuxSocket}\0${pane}`).digest("hex").slice(0, 24);
    socketPath = path2.join(directory, `${key}.sock`);
    const alive = await new Promise((resolve) => {
      const probe = request({ socketPath, path: "/", timeout: 300 }, (res) => {
        res.resume();
        resolve(true);
      });
      probe.on("timeout", () => {
        probe.destroy();
        resolve(true);
      });
      probe.on(
        "error",
        (error) => resolve(!["ENOENT", "ECONNREFUSED"].includes(error.code ?? ""))
      );
      probe.end();
    });
    if (alive) {
      closed = true;
      socketPath = void 0;
      return;
    }
    await unlink(socketPath).catch(() => {
    });
    server = createServer((req, res) => {
      let body = "";
      req.setEncoding("utf8");
      req.on("data", (part) => {
        body += part;
        if (Buffer.byteLength(body) > 1024 * 1024) req.destroy();
      });
      req.on("end", () => {
        try {
          const input = JSON.parse(body);
          if (req.method !== "POST" || req.url !== "/editor" || closed || waitingForUI || !context || input.version !== 1 || input.terminalSessionId !== terminalSessionId || input.threadId !== context.sessionManager.getSessionId() || input.instanceId !== instanceId || typeof input.requestId !== "string" || !input.requestId || typeof input.text !== "string")
            throw new Error("Pi editor identity mismatch");
          if (applied.has(input.requestId))
            throw new Error(
              "Pi editor request was already applied; inspect the terminal before retrying"
            );
          if (!applied.has(input.requestId)) {
            context.ui.setEditorText(input.text);
            applied.set(input.requestId, input.text);
            if (applied.size > 64) applied.delete(applied.keys().next().value);
          }
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ applied: true }));
        } catch {
          res.statusCode = 409;
          res.end(
            JSON.stringify({
              applied: false,
              error: "Pi editor unavailable or identity changed"
            })
          );
        }
      });
    });
    await new Promise((resolve, reject) => {
      server.once("error", reject);
      server.listen(socketPath, resolve);
    });
    ownsSocket = true;
    await chmod(socketPath, 384);
  }
  pi.on("session_start", async (event, ctx) => {
    if (!ctx.hasUI) {
      closed = true;
      return;
    }
    try {
      let directory = path2.dirname(realpathSync(process.argv[1]));
      let version = "";
      for (let depth = 0; depth < 5; depth++, directory = path2.dirname(directory)) {
        try {
          const pkg = JSON.parse(
            readFileSync(path2.join(directory, "package.json"), "utf8")
          );
          if (pkg.name === "@earendil-works/pi-coding-agent") {
            version = pkg.version;
            break;
          }
        } catch {
        }
      }
      const [major, minor, patch] = version.split(".").map(Number);
      if (major !== 0 || minor < 85 || minor === 85 && patch < 1)
        throw new Error("unsupported");
    } catch {
      closed = true;
      if (ctx.hasUI)
        ctx.ui.notify(
          "Runweave requires Pi 0.85.1 or a compatible 0.x release",
          "warning"
        );
      return;
    }
    context = ctx;
    const result = spawnSync(
      process.env.TMUX_BINARY || "tmux",
      [
        "-S",
        tmuxSocket,
        "display-message",
        "-p",
        "-t",
        pane,
        "#{@runweave_panel_id}"
      ],
      { encoding: "utf8", timeout: 1e3 }
    );
    const panelId = result.status === 0 ? result.stdout.trim() : "";
    if (!panelId) {
      closed = true;
      return;
    }
    process.env.RUNWEAVE_TERMINAL_PANEL_ID = panelId;
    await openEditor(ctx).catch(
      () => ctx.ui.notify("Runweave Pi editor unavailable", "warning")
    );
    publish(ctx, `session_start:${event.reason}`, "SessionStart", {
      source: event.reason === "resume" ? "resume" : "startup"
    });
  });
  pi.on("agent_start", (_event, ctx) => {
    runId ??= randomUUID();
    outcome = null;
    reply = "";
    publish(ctx, "agent_start", "UserPromptSubmit");
  });
  pi.on("message_start", (event, ctx) => {
    if (event.message.role === "user") {
      const content = event.message.content;
      const prompt = typeof content === "string" ? content : content.filter((part) => part.type === "text").map((part) => part.text).join("\n");
      publish(ctx, "user_message", "UserPromptSubmit", {
        prompt: prompt.slice(0, 8e3)
      });
    }
  });
  pi.on("message_end", (event) => {
    if (event.message.role !== "assistant") return;
    outcome = event.message.stopReason === "error" ? "failed" : event.message.stopReason === "aborted" ? "interrupted" : event.message.stopReason === "stop" ? "completed" : null;
    reply = event.message.content.filter((part) => part.type === "text").map((part) => part.text).join("\n").slice(0, 8e3);
  });
  pi.on("agent_settled", (_event, ctx) => {
    if (!ctx.isIdle() || !runId) return;
    publish(ctx, "agent_settled", "Stop", { last_assistant_message: reply });
    runId = null;
  });
  pi.on(
    "tool_execution_start",
    (event, ctx) => publish(ctx, "tool_execution_start", "PreToolUse", {
      tool_use_id: event.toolCallId,
      tool_name: event.toolName
    })
  );
  pi.on(
    "tool_execution_end",
    (event, ctx) => publish(ctx, "tool_execution_end", "PostToolUse", {
      tool_use_id: event.toolCallId,
      tool_name: event.toolName
    })
  );
  pi.on("ui_prompt_start", (_event, ctx) => {
    waitingForUI = true;
    publish(ctx, "ui_prompt_start", "AgentMetadata");
  });
  pi.on("ui_prompt_end", (_event, ctx) => {
    waitingForUI = false;
    publish(ctx, "ui_prompt_end", "AgentMetadata");
  });
  pi.on(
    "session_tree",
    (_event, ctx) => publish(ctx, "session_tree", "AgentMetadata")
  );
  pi.on(
    "model_select",
    (_event, ctx) => publish(ctx, "model_select", "AgentMetadata")
  );
  pi.on("session_shutdown", async () => {
    closed = true;
    context = void 0;
    if (server?.listening)
      await new Promise((resolve) => server.close(() => resolve()));
    if (ownsSocket && socketPath) await unlink(socketPath).catch(() => {
    });
    await transport.drain();
  });
}
function canonicalSessionFile(file) {
  if (!file) return null;
  try {
    return realpathSync(file);
  } catch {
    try {
      return path2.join(realpathSync(path2.dirname(file)), path2.basename(file));
    } catch {
      return file;
    }
  }
}
export {
  runweave as default
};
