export const TERMINAL_CLIPBOARD_IMAGE_MAX_BYTES = 100 * 1024 * 1024;

export const TERMINAL_CLIPBOARD_IMAGE_MAX_MIB =
  TERMINAL_CLIPBOARD_IMAGE_MAX_BYTES / (1024 * 1024);

const BASE64_EXPANSION_RATIO = 4 / 3;
const JSON_BODY_OVERHEAD_BYTES = 1024 * 1024;

export const TERMINAL_CLIPBOARD_IMAGE_JSON_LIMIT =
  Math.ceil(TERMINAL_CLIPBOARD_IMAGE_MAX_BYTES * BASE64_EXPANSION_RATIO) +
  JSON_BODY_OVERHEAD_BYTES;
