import { format } from "prettier";
import { readFileSync, writeFileSync } from "node:fs";
import { CONFIGURATION_FIELDS } from "../packages/shared/src/configuration/fields";
import { CONFIGURATION_DOMAIN_LABELS } from "../packages/shared/src/configuration/services";
import { CONFIGURATION_ENUMS, CONFIGURATION_CREDENTIAL_GROUPS, configurationNumberRange, configurationOwnedPath, configurationServiceOrigin } from "../packages/shared/src/configuration/constraints";

const target = new URL("../docs/cli/configuration-reference.md", import.meta.url);
const lines = [
  "# 配置字段参考", "",
  "<!-- Generated by pnpm configuration:docs. Do not edit by hand. -->", "",
  "由共享字段注册表和校验元数据生成；操作与生效规则见 [配置 CLI](./configuration.md)，服务诊断见 [服务管理](./service-management.md)。", "",
  "所有字段以实例 settings.yaml 为唯一保存来源。缺失或 null 恢复默认，false、0、空字符串和空数组保留显式值。", "",
  "`<name>`、`<id>` 等是动态键占位，`[]` 表示数组成员；查询或修改时使用实际键和索引，键内的点与反斜杠需转义。", "",
  "下列约束反映配置文件校验；业务消费者可能有额外检查，配置校验通过不能代替真实功能验收。", "",
  "## 跨字段与特殊约束", "",
  ...Object.entries(CONFIGURATION_CREDENTIAL_GROUPS).map(([domain, keys]) => `- ${domain}：${keys.join("、")} 任一已设置时，所有成员都必须是非空字符串。`),
  "- agents.team.roles：provider 为 codex 或 traex，model 非空；codex 要求 fast 为布尔值且不能设置 max，traex 要求 max 为布尔值且不能设置 fast。",
  "- services.feishu.legacyWebhook.url：HTTPS，无用户信息和 fragment。",
  "- 敏感字段拒绝把脱敏占位符当成实际凭据。初始化、迁移和消费者检查见 [配置 CLI](./configuration.md)。", "",
];
const cell = (value: unknown) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
for (const domain of [...new Set(CONFIGURATION_FIELDS.map(field => field.domain))]) {
  lines.push(`## ${CONFIGURATION_DOMAIN_LABELS[domain] ?? domain}`, "", `配置域：\`${domain}\`。`, "");
  for (const field of CONFIGURATION_FIELDS.filter(field => field.domain === domain)) {
    const range = configurationNumberRange(field.path);
    const constraints = [
      CONFIGURATION_ENUMS[field.path] ? `枚举：${CONFIGURATION_ENUMS[field.path]!.join("、")}` : undefined,
      range.min !== undefined ? `≥ ${range.min}` : undefined,
      range.max !== undefined ? `≤ ${range.max}` : undefined,
      range.exclusiveMin !== undefined ? `> ${range.exclusiveMin}` : undefined,
      configurationOwnedPath(field.path) ? "绝对路径，必须属于所选实例" : undefined,
      configurationServiceOrigin(field.path) ? "HTTPS origin；无用户信息、query、fragment，路径只能是 /" : undefined,
    ].filter(Boolean).join("；") || "按字段类型校验";
    lines.push(`### ${field.path}`, "", field.description, "", "| 属性 | 合同 |", "| --- | --- |",
      `| 类型 | ${field.type}；允许 null 恢复默认 |`,
      `| 默认 | ${cell("rule" in field.default ? field.default.rule : JSON.stringify(field.default.value))} |`,
      `| 所属模块 | ${cell(field.owner)} |`,
      `| 生效 | ${field.apply === "reload" ? "所属消费者重载" : "所属进程重启"} |`,
      `| 敏感 / 远端可修改 | ${field.sensitive ? "是" : "否"} / ${field.remote ? "是" : "否"} |`,
      `| 约束 | ${cell(constraints)} |`,
      `| 显式迁移来源 | ${cell(field.migrationSources.join("、"))} |`, "");
  }
}
async function writeReference() {
const output = await format(lines.join("\n"), { parser: "markdown" });
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output) throw new Error("配置参考已过期，请运行 pnpm configuration:docs");
} else writeFileSync(target, output);
console.log(`Configuration reference: ${CONFIGURATION_FIELDS.length} fields (${process.argv.includes("--check") ? "checked" : "generated"}).`);

}
void writeReference();
