import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { bridgeAssets } from "../../packages/agent-bridge/src/install-pi.mjs";

const root = fileURLToPath(new URL("../../", import.meta.url));
const { build } = createRequire(path.join(root, "electron/package.json"))(
  "esbuild",
);

export async function buildAgentAssets() {
  const piDist = path.join(root, "plugins/pi/dist");
  const electronPi = path.join(root, "electron/resources/hooks/pi");
  const destinations = [
    "plugins/toolkit/hooks",
    "electron/resources/hooks",
    "plugins/pi/dist/bridge",
    "electron/resources/hooks/pi/bridge",
  ];
  for (const destination of destinations) {
    await mkdir(path.join(root, destination), { recursive: true });
    for (const asset of bridgeAssets) {
      await copyFile(
        path.join(root, "packages/agent-bridge/hooks", asset),
        path.join(root, destination, asset),
      );
    }
  }
  const result = await build({
    absWorkingDir: root,
    entryPoints: [path.join(root, "plugins/pi/extensions/runweave.ts")],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    write: false,
    legalComments: "none",
    banner: {
      js: "// Runweave managed Pi extension. Generated by pnpm agents:build; do not edit.",
    },
  });
  for (const destination of [piDist, electronPi]) {
    await writeFile(
      path.join(destination, "runweave.js"),
      result.outputFiles[0].text,
    );
    await copyFile(
      path.join(root, "plugins/pi/skills/runweave/SKILL.md"),
      path.join(destination, "SKILL.md"),
    );
  }
  // Codex/Traex dispatch remains a native Toolkit entry point.
  await copyFile(
    path.join(root, "plugins/toolkit/hooks/runweave-hook-dispatch.cjs"),
    path.join(root, "electron/resources/hooks/runweave-hook-dispatch.cjs"),
  );
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  await buildAgentAssets();
  console.log("Agent bridge and Pi distribution built.");
}
